# Generated by Django 5.2.9 on 2026-06-28 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventtickettier_ticketpurchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketpurchase',
            name='qr_code',
        ),
    ]
