# Generated by Django 5.2.9 on 2026-06-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_ticketpurchase_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='funds_transferred_to_venue',
            field=models.BooleanField(default=False),
        ),
    ]
