# Generated by Django 5.2.9 on 2026-07-04 09:29

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_ticketpurchase_funds_transferred_to_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='custom_venue_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='dress_code',
            field=models.CharField(choices=[('Upscale Nightclub', 'Upscale Nightclub'), ('Casual', 'Casual'), ('Smart Casual', 'Smart Casual'), ('Rave / Creative', 'Rave / Creative'), ('Pool Attire', 'Pool Attire'), ('Black Tie', 'Black Tie'), ('No Dress Code', 'No Dress Code')], default='No Dress Code', max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='eventtickettier',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='EventLineup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=255)),
                ('artist_image', models.ImageField(blank=True, null=True, upload_to='events/lineup/')),
                ('role', models.CharField(choices=[('headliner', 'Headliner'), ('co_headliner', 'Co-Headliner'), ('support', 'Support')], default='support', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup', to='events.event')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
