# Generated by Django 5.2.9 on 2026-07-11 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_stripewebhookevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrsvp',
            name='status',
        ),
    ]
