# Generated by Django 5.2.9 on 2026-07-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_eventrsvp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
