# Generated by Django 5.2.9 on 2026-07-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_ticketpurchase_base_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketpurchase',
            name='is_scanned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketpurchase',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
