# Generated by Django 5.2.9 on 2026-06-23 06:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.PositiveIntegerField()),
                ('execution_time_ms', models.FloatField(help_text='Execution time in milliseconds')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['path'], name='security_au_path_9b1d46_idx'), models.Index(fields=['status_code'], name='security_au_status__03ea75_idx'), models.Index(fields=['timestamp'], name='security_au_timesta_82ac0d_idx')],
            },
        ),
    ]
