# Generated by Django 5.2.9 on 2026-07-16 09:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0009_ticketpurchase_is_scanned_ticketpurchase_scanned_at'),
        ('venues', '0006_venue_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_messages', to='events.event')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_venue_messages', to=settings.AUTH_USER_MODEL)),
                ('sender_venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='venues.venue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
