# Generated by Django 5.2.9 on 2026-07-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_faq_legaldocument_bugreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legaldocument',
            name='document_type',
            field=models.CharField(choices=[('terms', 'Terms of Service'), ('privacy', 'Privacy Policy'), ('guidelines', 'Community Guidelines')], max_length=20),
        ),
    ]
