# Generated by Django 5.2.9 on 2026-06-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='otp_type',
            field=models.CharField(choices=[('register', 'Registration'), ('reset', 'Password Reset')], default='register', max_length=20),
        ),
    ]
