# Generated by Django 5.2.9 on 2026-06-23 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_bio_user_profile_image_userreport_userblock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='location_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_activity_status_visible', models.BooleanField(default=True)),
                ('is_location_shared', models.BooleanField(default=True)),
                ('is_nightlife_score_visible', models.BooleanField(default=True)),
                ('allow_tagging', models.BooleanField(default=True)),
                ('allow_messages_from_non_followers', models.BooleanField(default=False)),
                ('nightlife_score', models.IntegerField(default=0)),
                ('notify_likes', models.BooleanField(default=True)),
                ('notify_comments', models.BooleanField(default=True)),
                ('notify_new_followers', models.BooleanField(default=True)),
                ('notify_messages', models.BooleanField(default=True)),
                ('notify_events_rsvps', models.BooleanField(default=True)),
                ('notify_heatmap_alerts', models.BooleanField(default=True)),
                ('notify_promotions', models.BooleanField(default=False)),
                ('notify_sms', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
