# Generated by Django 5.2.9 on 2026-06-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_cover_image_user_location_name_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('regular', 'Regular User'), ('venue', 'Venue Account')], default='regular', max_length=20),
        ),
    ]
