# Generated by Django 5.2.9 on 2026-06-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='is_user_profile_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_type',
            field=models.CharField(choices=[('user', 'Regular User'), ('venue', 'Venue Account')], default='user', max_length=20),
        ),
    ]
