# Generated by Django 5.2.9 on 2026-06-27 09:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Venue Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='venue',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='venues/covers/'),
        ),
        migrations.AddField(
            model_name='venue',
            name='price_tier',
            field=models.IntegerField(blank=True, choices=[(1, '$'), (2, '$$'), (3, '$$$'), (4, '$$$$')], null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='venues/profiles/'),
        ),
        migrations.AddField(
            model_name='venuestatistic',
            name='followers_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venuestatistic',
            name='heat_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='venues', to='venues.venuecategory'),
        ),
        migrations.CreateModel(
            name='VenueFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_follows', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='venues.venue')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'venue')},
            },
        ),
    ]
