# Generated by Django 5.2.9 on 2026-06-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_alter_venue_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
