# Generated by Django 5.2.9 on 2026-06-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_venue_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='stripe_account_status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
