# Generated by Django 5.2.9 on 2026-07-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0005_venue_stripe_account_id_venue_stripe_account_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
