# Generated by Django 5.2.9 on 2026-07-13 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_remove_post_mood_post_shares_count_post_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mood',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
