# Generated by Django 5.2.9 on 2026-07-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_post_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='social/thumbnails/'),
        ),
        migrations.AddField(
            model_name='story',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='social/thumbnails/'),
        ),
    ]
