# Generated by Django 5.2.9 on 2026-07-14 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_postmedia_thumbnail_story_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='bg_color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='text_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text')], default='image', max_length=10),
        ),
        migrations.AlterField(
            model_name='story',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='social/stories/'),
        ),
        migrations.AlterField(
            model_name='story',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('text', 'Text')], default='image', max_length=10),
        ),
    ]
