# Generated by Django 5.2.9 on 2026-07-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('system', 'System'), ('event_rsvp', 'Event RSVP'), ('ticket_purchase', 'Ticket Purchase'), ('like', 'Like'), ('comment', 'Comment'), ('new_follower', 'New Follower'), ('message', 'Message'), ('promotion', 'Promotion'), ('heatmap_alert', 'Heat Map Alert'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
